spring:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:android}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_USERNAME:cataclysm91}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: ${MAX_FILE_TRESHOLD:300MB}
      max-request-size: ${MAX_REQUEST_SIZE:300MB}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:blendicav@gmail.com}
    password: ${MAIL_PASSWORD:wxydcauzgxrmawui}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

app:
  auth:
    tokenSecret: ${TOKEN_SECRET:926D96C90030DD58429D2751AC1BDBBC}
    tokenExpirationMsec: 3600000

  oauth2:
    authorizedRedirectUris:
      - ${REDIRECT_URI_01:http://localhost:3000/oauth2/redirect}

file:
  upload-dir: users

logging:
  level:
    org:
      hibernate:
        type: error
        SQL: error


init:
  userpass: ${INIT_USERPASS:parola}
  loadmock: ${LOAD_MOCK:false}

