POST {{luci_url}}/admin/upload_professors
Authorization: Bearer {{temp_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="professors.csv"
Content-Type: text/csv

< ../../../data/professors.csv
--WebAppBoundary--
Content-Disposition: form-data; name="sendEmails";

true
--WebAppBoundary--

###