POST {{luci_url}}/admin/upload_specializations
Authorization: Bearer {{temp_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="specializations.csv"
Content-Type: text/csv

< ../../../data/specializations.csv
--WebAppBoundary--

###