POST {{luci_url}}/admin/upload_disciplines
Authorization: Bearer {{temp_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="disciplines.csv"
Content-Type: text/csv

< ../../../data/disciplines.csv
--WebAppBoundary--

###