POST {{luci_url}}/admin/upload_groups
Authorization: Bearer {{temp_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="groups.csv"
Content-Type: text/csv

< ../../../data/groups.csv
--WebAppBoundary--

###