POST {{local_url}}/grades/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{temp_token}}

{
  "mark": 10,
  "examDate": "2021-01-10 12:55:09",
  "exam": 2,
  "student": 1
}